### ISSUE TITLE
Mountain car example is not deterministic

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#202]
Running the mountain_car example twice in a row yields different results:
![mountain_car](https://user-images.githubusercontent.com/6512628/88252729-36ade100-ccea-11ea-9fa0-38676e2c283c.png)

In addition, I also observed runs where the environment was not solved by the found champion.

I think the example should behave deterministic, so we should fix this.

**Comment by HenrikMettler** [comment]
I think this can be fixed by setting the env.seed before sampling the observation in the inner objective function: 
```python
    env.seed(seed)
    observation = env.reset()
```
here: https://github.com/Happy-Algorithms-League/hal-cgp/blob/e121b96d4311d1f37abc4eede580df767cda9ce5/examples/example_mountain_car.py#L64`

(I tested with 2 seeds for 2 runs each and the results within the seed were both times identical)

**Comment by mschmidt87** [comment]
Great, thanks for the investigation. Can I assign the ticket to you and ask you to create a PR since you already did the investigation? Thanks.
