### ISSUE TITLE
how to pass in a column of a dataset?

### ISSUE THREAD

**Issue by z3fei** [Happy-Algorithms-League/hal-cgp#340]
Hi, can you point me to an example where i can evaluate the individuals by passing a set of columns from my dataset using hal-cgp? many thanks!

In example_caching.py

def objective(individual):
    if not individual.fitness_is_None():
        return individual

    individual.fitness = -inner_objective(individual)

    return individual

--below command calls the objective function to pass in the individual, can i know how do i pass in the features of my dataset to be evaluated? 
cgp.evolve(pop, objective, ea, **params["evolve_params"], print_progress=True)

**Comment by jakobj** [comment]
dear @z3fei, indeed it seems like a simple example of using `to_numpy()` was missing. I've created a pull request here https://github.com/Happy-Algorithms-League/hal-cgp/pull/341 which you can have a look at.

In general, instead of transforming an individual into a regular Python function which only accepts scalars (`individual.to_func()`) you should use `individual.to_numpy()` in your objective to create a NumPy-compatible function. To this you can then pass NumPy arrays, e.g., `y = f(x[:, 0], x[:, 1])` to pass the first two columns of dataset `x` to a function. Note that in this case, `y` will be a vector of the same length as one column.

**Comment by z3fei** [comment]
thank you @jakobj for coming back to me so soon and with a NumPy example! i'll revisit this again later of the week.
